---
title: "4 - Linear Models"
output: 
  pdf_document: 
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(rethinking)
```

### 4.1.1. Normal by addition 

```{r}
# 4.1
pos <- replicate(1000, sum(runif(16, -1, 1)))
par(mfrow=c(1, 2))
dens(pos, norm.comp = T)
dens(replicate(10000, sum(runif(256, -1, 1))), norm.comp = T)
```

### 4.1.2. Normal by multiplication

```{r}
# 4.2
dens(replicate(1e4, prod(1 + runif(12, 0, 0.1))), norm.comp = T)
```

```{r}
# 4.4
big <- replicate(1e4, prod(1 + runif(12, 0, 0.5)))
small <- replicate(1e4, prod(1 + runif(12, 0, 0.01)))
par(mfrow=c(1, 2))
dens(big, norm.comp = T, main = "Big")
dens(small, norm.comp = T, main = "Small")
```

### Normal by log-multiplication

```{r}
# 4.5
big <- replicate(1e4, prod(1 + runif(12, 0, 1)))
log_big <- log(big)
par(mfrow=c(1, 2))
dens(big, norm.comp = T, main = "Big")
dens(log_big, norm.comp = T, main = "log(Big)")
```

## 4.3 A Gaussian model of height
```{r}
# 4.7
library(rethinking)
data(Howell1)
d <- Howell1
```

```{r}
# 4.8
str(d)
```

We want heights of adults only (352 rows):
```{r}
# 4.10
d2 <- d[d$age >= 18, ]
```

### 4.3.2 The model

Height mean:

```{r}
# 4.11
curve(dnorm(x, 178, 20), from=100, to=250)
```

Height standard deviation:
```{r}
# 4.12
curve(dunif(x, 0, 50), from=10, to=60)
```

```{r}
# 4.13
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```

